{{- if .Values.postgis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "geocoder.fullname" . }}-postgis
  labels:
    {{- include "geocoder.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.postgis.auth.username | quote }}
  password: {{ .Values.postgis.auth.password | quote }}
  database: {{ .Values.postgis.auth.database | quote }}
{{- end }}
